name: Build and publish docker image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          submodules: recursive
          fetch-depth: '0'
        
      - name: install build dependencies
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env

      - name: build artifacts
        run: |
          cargo install cross
          targets=(
            "aarch64-unknown-linux-gnu"
            "x86_64-pc-windows-gnu"
          )

          for target in "${targets[@]}" ; do
            cross build --target ${target} --release
          done

      - name: copy the binaries to releases folder
        run: |
          rm -rf ./target/debug ./target/release
          mkdir ./target/releases

          # https://stackoverflow.com/questions/216995/how-can-i-use-inverse-or-negative-wildcards-when-pattern-matching-in-a-unix-linu
          shopt -s extglob

          for target_dir in ./target/* ; do
            target_dir_name=$(basename $target_dir)
            if [ ${target_dir_name} != "releases" ]; then 
              for artifact in ./target/${target_dir_name}/release/chunk-search-rs* ; do
                artifact_name=$(basename $artifact)
                if [ ${artifact_name} != "chunk-search-rs.d" ]; then
                  cp ./target/${target_dir_name}/release/${artifact_name} ./target/releases/${target_dir_name}-${artifact_name}
                fi
              done
            fi
          done

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "minor"
          WITH_V: true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/releases/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Image to GPR
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          IMAGE_NAME: 'chunk-search-rs'
          DOCKERFILE_PATH: './docker/single-target/Dockerfile'
          BUILD_CONTEXT: './'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
