name: Build and publish docker image
on:
  push:
    branches:
      - master
jobs:
  build-and-release:
    name: Build binary and make a release on GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
          fetch-depth: '0'
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Build artifact
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
          WITH_V: true
          DEFAULT_BRANCH: "master"
        id: bump_version
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/release/chunk-search-rs
          draft: false
          prerelease: false
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-docker-image:
    runs-on: ubuntu-latest
    env:
      image_name: chunk-search-rs
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: '0'
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.image_name }}
          tags: |
            type=sha,prefix=sha-,suffix=,format=short
            type=raw,value=latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./docker/single-target/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
